In [1]:
import sys
# на уровень выше из research_rank/
sys.path.insert(0, '..')
from pathlib import Path
import numpy as np
import pandas as pd
import json
from collections import defaultdict
from plot_json import convert_dictlist_to_matrix
import matplotlib.pyplot as plt

Рассмотрим критерий основанный на матрице информации H, для которой протокол считается полным, если $r^2$ собственных значений равно 0, а (2s-r)r строго > 0. Для начала рассмотрим протокол приведённый в статье "Statistical reconstruction of qutrits"(2004), https://sci-hub.ru/https://doi.org/10.1103/PhysRevA.70.042303 .

In [2]:
from purification_state import*
rank = [1,2,3]
dim = 3
for r in rank:
    pure_class = Purification(rank = r, dimension = dim)
    val = (np.real(np.round(pure_class.value_matrix_information(), 14)))
    val = list(np.sign(val))
    numb_zero = val.count(0)
    numb_positiv = val.count(1)
    
    print(f"Количество теоретических нулей = {r**2}, количество нулей для протокола = {numb_zero}")
    print(f"Количество теоретических положительных чисел = {(2*dim-r)*r}, количество положительных чисел для протокола = {numb_positiv}")

1 1
Количество теоретических нулей = 1, количество нулей для протокола = 1
Количество теоретических положительных чисел = 5, количество положительных чисел для протокола = 5
2 2
Количество теоретических нулей = 4, количество нулей для протокола = 4
Количество теоретических положительных чисел = 8, количество положительных чисел для протокола = 8
3 3
Количество теоретических нулей = 9, количество нулей для протокола = 9
Количество теоретических положительных чисел = 9, количество положительных чисел для протокола = 9


Теперь посчитаем для наших протоколов. Для протокола с пластинкой $\lambda/4$.

In [3]:
rank = [1,2,3]
dim = 3
for r in rank:
    start_protocol = [Gl_4(0),Gl_4(np.pi/8),Gl_4(3*np.pi/8),Gl_4(5*np.pi/8),Gl_4(7*np.pi/8)]
    pure_class = Purification(rank = r, dimension = dim, protocol = start_protocol)
    val = (np.real(np.round(pure_class.value_matrix_information(), 15)))
    print(np.round(sorted(val),16))
    val = list(np.sign(val))
    numb_zero = val.count(0)
    numb_positiv = val.count(1)
    print(f"Количество теоретических нулей = {r**2}, количество нулей для протокола = {numb_zero}")

1 1
[0.         1.87607388 2.65865459 3.82948457 5.2641151  6.37167186]
Количество теоретических нулей = 1, количество нулей для протокола = 1
2 2
[0.         0.         0.         0.         0.16251423 0.63548014
 1.05163579 1.19167752 2.25668276 3.90867974 4.45651436 6.33681545]
Количество теоретических нулей = 4, количество нулей для протокола = 4
3 3
[ 0.         -0.         -0.         -0.          0.         -0.
 -0.         -0.          0.          0.          0.14238358  0.94055175
  0.99026737  2.26184745  2.42710366  2.6862332   4.48396398  6.06764901]
Количество теоретических нулей = 9, количество нулей для протокола = 10


Для протокола с пластинкой $\lambda/4$ без одного измерения.

In [276]:
rank = [1,2,3]
dim = 3
for r in rank:
    start_protocol = [Gl_4(0), Gl_4(np.pi/8), Gl_4(3*np.pi/8), Gl_4(5*np.pi/8)]
    pure_class = Purification(rank = r, dimension = dim, protocol = start_protocol)
    val = (np.real(np.round(pure_class.value_matrix_information(), 14)))
    print(np.round(sorted(val),5))
    val = list(np.sign(val))
    numb_zero = val.count(0)
    numb_positiv = val.count(1)
    print(f"Количество теоретических нулей = {r**2}, количество нулей для протокола = {numb_zero}")

[0.      0.97449 1.79753 2.94309 4.36882 5.91607]
Количество теоретических нулей = 1, количество нулей для протокола = 1
[ 0.      -0.       0.       0.       0.       0.26503  0.53812  1.0986
  1.83556  2.73459  4.53726  4.99084]
Количество теоретических нулей = 4, количество нулей для протокола = 5
[ 0.       0.       0.       0.      -0.      -0.      -0.      -0.
 -0.       0.       0.       0.3749   0.71815  1.13524  1.82337  2.71533
  4.04412  5.18888]
Количество теоретических нулей = 9, количество нулей для протокола = 11


Для протокола Фёдорова.

In [310]:
rank = [1,2,3]
dim = 3
for r in rank:
    start_protocol = [np.diag((1,1,1)), Gl_2(np.pi/8), Gl_8(0) @ Gl_2(np.pi/8)]
    pure_class = Purification(rank = r, dimension = dim, protocol = start_protocol)
    val = (np.real(np.round(pure_class.value_matrix_information(), 14)))
    print(np.round(sorted(val),16))
    val = list(np.sign(val))
    numb_zero = val.count(0)
    numb_positiv = val.count(1)
    print(f"Количество теоретических нулей = {r**2}, количество нулей для протокола = {numb_zero}")

[0.         0.28654215 0.84110661 2.03810149 3.66116786 5.17308189]
Количество теоретических нулей = 1, количество нулей для протокола = 1
[-0.         -0.          0.          0.          0.         -0.
  0.21576386  0.62669859  1.2499792   1.85479194  3.41606447  4.63670194]
Количество теоретических нулей = 4, количество нулей для протокола = 6
[ 0.         -0.         -0.          0.          0.          0.
  0.          0.         -0.         -0.         -0.         -0.
  0.25630945  0.36680748  0.87429108  2.01078937  3.6760067   4.81579592]
Количество теоретических нулей = 9, количество нулей для протокола = 12


Для протокола Фёдорова + измерение из протокола $\frac{\lambda}{4}$

In [327]:
rank = [1,2,3]
dim = 3
for angle in [0, 1, 3, 5, 7]:
    print(f"\n\n Для угла {angle} ⋅ π/8")
    for r in rank:
        start_protocol = [np.diag((1,1,1)), Gl_2(np.pi/8), Gl_8(0) @ Gl_2(np.pi/8), Gl_4(angle * np.pi/8)]
        pure_class = Purification(rank = r, dimension = dim, protocol = start_protocol)
        val = (np.real(np.round(pure_class.value_matrix_information(), 14)))
        # print(np.round(sorted(val),16))
        val = list(np.sign(val))
        numb_zero = val.count(0)
        numb_positiv = val.count(1)
        print(f"Количество теоретических нулей = {r**2}, количество нулей для протокола = {numb_zero}")



 Для угла 0 ⋅ π/8
Количество теоретических нулей = 1, количество нулей для протокола = 1
Количество теоретических нулей = 4, количество нулей для протокола = 6
Количество теоретических нулей = 9, количество нулей для протокола = 12


 Для угла 1 ⋅ π/8
Количество теоретических нулей = 1, количество нулей для протокола = 1
Количество теоретических нулей = 4, количество нулей для протокола = 5
Количество теоретических нулей = 9, количество нулей для протокола = 11


 Для угла 3 ⋅ π/8
Количество теоретических нулей = 1, количество нулей для протокола = 1
Количество теоретических нулей = 4, количество нулей для протокола = 5
Количество теоретических нулей = 9, количество нулей для протокола = 11


 Для угла 5 ⋅ π/8
Количество теоретических нулей = 1, количество нулей для протокола = 1
Количество теоретических нулей = 4, количество нулей для протокола = 5
Количество теоретических нулей = 9, количество нулей для протокола = 11


 Для угла 7 ⋅ π/8
Количество теоретических нулей = 1, количест

Проверка всех переборов элементов протокола для выбора 3 элементов 

In [314]:
import itertools

rank = [1,2,3]
dim = 3
all_prot = [np.diag((1,1,1)), Gl_2(np.pi/8), Gl_8(0) @ Gl_2(np.pi/8), Gl_4(0), Gl_4(np.pi/8), Gl_4(3*np.pi/8), Gl_4(5*np.pi/8), Gl_4(7*np.pi/8)]

for triple in itertools.combinations(list(range(len(all_prot))), 3):
    ind_1, ind_2, ind_3 = triple
    print(f"\n\n Индексы элементов протокола: {ind_1, ind_2, ind_3}")
    for r in rank:
        start_protocol = [all_prot[ind_1], all_prot[ind_2], all_prot[ind_3]]
        pure_class = Purification(rank = r, dimension = dim, protocol = start_protocol)
        val = (np.real(np.round(pure_class.value_matrix_information(), 14)))
        # print(np.round(sorted(val),16))
        val = list(np.sign(val))
        numb_zero = val.count(0)
        numb_positiv = val.count(1)
        print(f"Количество теоретических нулей = {r**2}, количество нулей для протокола = {numb_zero}")



 Индексы элементов протокола: (0, 1, 2)
Количество теоретических нулей = 1, количество нулей для протокола = 1
Количество теоретических нулей = 4, количество нулей для протокола = 6
Количество теоретических нулей = 9, количество нулей для протокола = 12


 Индексы элементов протокола: (0, 1, 3)
Количество теоретических нулей = 1, количество нулей для протокола = 2
Количество теоретических нулей = 4, количество нулей для протокола = 8
Количество теоретических нулей = 9, количество нулей для протокола = 14


 Индексы элементов протокола: (0, 1, 4)
Количество теоретических нулей = 1, количество нулей для протокола = 1
Количество теоретических нулей = 4, количество нулей для протокола = 6
Количество теоретических нулей = 9, количество нулей для протокола = 12


 Индексы элементов протокола: (0, 1, 5)
Количество теоретических нулей = 1, количество нулей для протокола = 1
Количество теоретических нулей = 4, количество нулей для протокола = 6
Количество теоретических нулей = 9, количество н

Проверка всех переборов элементов протокола для выбора 4 элементов 

In [315]:
import itertools

rank = [1,2,3]
dim = 3
all_prot = [np.diag((1,1,1)), Gl_2(np.pi/8), Gl_8(0) @ Gl_2(np.pi/8), Gl_4(0), Gl_4(np.pi/8), Gl_4(3*np.pi/8), Gl_4(5*np.pi/8), Gl_4(7*np.pi/8)]

for triple in itertools.combinations(list(range(len(all_prot))), 4):
    ind_1, ind_2, ind_3, ind_4 = triple
    print(f"\n\n Индексы элементов протокола: {ind_1, ind_2, ind_3, ind_4}")
    for r in rank:
        start_protocol = [all_prot[ind_1], all_prot[ind_2], all_prot[ind_3], all_prot[ind_4]]
        pure_class = Purification(rank = r, dimension = dim, protocol = start_protocol)
        val = (np.real(np.round(pure_class.value_matrix_information(), 14)))
        # print(np.round(sorted(val),16))
        val = list(np.sign(val))
        numb_zero = val.count(0)
        numb_positiv = val.count(1)
        print(f"Количество теоретических нулей = {r**2}, количество нулей для протокола = {numb_zero}")



 Индексы элементов протокола: (0, 1, 2, 3)
Количество теоретических нулей = 1, количество нулей для протокола = 1
Количество теоретических нулей = 4, количество нулей для протокола = 6
Количество теоретических нулей = 9, количество нулей для протокола = 12


 Индексы элементов протокола: (0, 1, 2, 4)
Количество теоретических нулей = 1, количество нулей для протокола = 1
Количество теоретических нулей = 4, количество нулей для протокола = 5
Количество теоретических нулей = 9, количество нулей для протокола = 11


 Индексы элементов протокола: (0, 1, 2, 5)
Количество теоретических нулей = 1, количество нулей для протокола = 1
Количество теоретических нулей = 4, количество нулей для протокола = 5
Количество теоретических нулей = 9, количество нулей для протокола = 11


 Индексы элементов протокола: (0, 1, 2, 6)
Количество теоретических нулей = 1, количество нулей для протокола = 1
Количество теоретических нулей = 4, количество нулей для протокола = 5
Количество теоретических нулей = 9, 

Мой протокол

In [220]:
rank = [1,2,3]
dim = 3
for r in rank:
    start_protocol = [Gl_4(np.pi / 8) @ Gl_8(0), Gl_4(0) @ Gl_8(np.pi / 8), Gl_4(0) @ Gl_8(0)]
    pure_class = Purification(rank = r, dimension = dim, protocol = start_protocol)
    val = (np.real(np.round(pure_class.value_matrix_information(), 14)))
    print(np.round(sorted(val),16))
    val = list(np.sign(val))
    numb_zero = val.count(0)
    numb_positiv = val.count(1)
    print(f"Количество теоретических нулей = {r**2}, количество нулей для протокола = {numb_zero}")

[0.         0.00938848 0.39227146 1.06652339 4.93679738 5.5950193 ]
Количество теоретических нулей = 1, количество нулей для протокола = 1
[-0.         -0.          0.         -0.         -0.          0.
  0.28376907  0.32056006  0.87564888  0.95551402  4.72985349  4.83465447]
Количество теоретических нулей = 4, количество нулей для протокола = 6
[-0.          0.          0.          0.          0.         -0.
  0.         -0.         -0.          0.          0.          0.
  0.19839147  0.32099551  0.6170294   1.10477778  4.6685191   5.09028674]
Количество теоретических нулей = 9, количество нулей для протокола = 12
