In [1]:
import sys
# на уровень выше из research_rank/
sys.path.insert(0, '..')
from pathlib import Path
import numpy as np
import pandas as pd
import json
from collections import defaultdict
from plot_json import convert_dictlist_to_matrix
import matplotlib.pyplot as plt

/Users/denis/Desktop/VS code projects/Quantum_tools/Tomography/src/research_data/../Adaptive_compresive_cending_qutrit.py:379: SyntaxWarning: invalid escape sequence '\m'
  label='$S_{\mathrm{cvx}} \pm$ std')
/Users/denis/Desktop/VS code projects/Quantum_tools/Tomography/src/research_data/../Adaptive_compresive_cending_qutrit.py:386: SyntaxWarning: invalid escape sequence '\m'
  ax1.set_ylabel('$S_{\mathrm{cvx}}$')


(CVXPY) Aug 01 05:02:23 PM: Encountered unexpected exception importing solver MOSEK:
AttributeError("module 'mosek' has no attribute 'conetype'")


In [ ]:

from Qutrit import*
from Adaptive_compresive_cending_qutrit import*
plt.rcParams.update({
    'font.size': 16,               # Размер шрифта по умолчанию
    'axes.titlesize': 16,          # Размер заголовка
    'axes.labelsize': 16,          # Размер подписей осей
    'xtick.labelsize': 16,         # Размер цифр на оси X
    'ytick.labelsize': 16,         # Размер цифр на оси Y
    'legend.fontsize': 16          # Размер шрифта легенды
})
# q1 = -10.0; q2 = 85.8; q3 = 43.2
# new_matr =  Gl_4(q2 * np.pi / 180) @ Gl_2(q1 * np.pi / 180) @ Gl_4(q3 * np.pi / 180) 
# new_el = [0]*3
# for i in range(3):
#     new_el[i] = np.array(np.conj(new_matr).T @ A00[i] @ new_matr)

protocol = [Gl_2(pi / 8) @ Gl_8(0), Gl_2(pi / 8), np.diag((1,1,1))]

tomography_1 = ACT(protocol, 1, 3)

x = np.array([1, 2, 3])
svx_list = []         
fidelity_list = []
N = 10


for i in tqdm(range(N)):
    svx_list_one_measurement, fidelity_list_one_measurement, fidelity_x_min, fidelity_x_max, x_min_list, x_max_list, state_ml = tomography_1.main(epsilon=10**-5)
    for ind_min in range(len(x_min_list)):
        x_min_list[ind_min] = np.array([[complex(item) for item in row] for row in x_min_list[ind_min]])
    for ind_max in range(len(x_max_list)):
        x_max_list[ind_max] = np.array([[complex(item) for item in row] for row in x_max_list[ind_max]])
    
    fidelity_list_xmax_xmin = [tomography_1.Fidelity(x_min_list[0], x_max_list[0]), tomography_1.Fidelity(x_min_list[1], x_max_list[1]), tomography_1.Fidelity(x_min_list[2], x_max_list[2])]#, tomography_1.Fidelity(x_min_list[3], x_max_list[3])] 
    if svx_list_one_measurement is not np.inf :
        svx_list.append(svx_list_one_measurement)
        fidelity_list.append(np.abs(fidelity_list_xmax_xmin))

y = np.mean(np.array(svx_list),axis = 0)
std = np.std(np.array(svx_list),axis = 0)
fidelity_mean = np.mean((fidelity_list), axis = 0)
fidelity_std = np.std(np.array(fidelity_list),axis = 0)


print("Mean fidelity:", fidelity_mean , "\tStd fidelity:", fidelity_std)
print("Mean svx for protocol:", y,"\tStd s_cvx for protocol:", std)
print()
pl_fid_s_cvx(x, y, std, fidelity_mean, fidelity_std)

  0%|          | 0/10 [00:00<?, ?it/s]

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[[1 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 1 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 1]]]


 10%|█         | 1/10 [00:03<00:28,  3.18s/it]

Время выполнения: 3.056241 секунд
[[-5.00000000e-01+0.j -7.07106781e-01+0.j -5.00000000e-01+0.j]
 [-7.07106781e-01+0.j  2.22044605e-16+0.j  7.07106781e-01+0.j]
 [-5.00000000e-01-0.j  7.07106781e-01+0.j -5.00000000e-01-0.j]]
[[-5.00000000e-01+0.j -7.07106781e-01+0.j -5.00000000e-01+0.j]
 [-7.07106781e-01+0.j  2.22044605e-16+0.j  7.07106781e-01+0.j]
 [-5.00000000e-01-0.j  7.07106781e-01+0.j -5.00000000e-01-0.j]]
[[-5.00000000e-01+0.j -7.07106781e-01+0.j -5.00000000e-01+0.j]
 [-7.07106781e-01+0.j  2.22044605e-16+0.j  7.07106781e-01+0.j]
 [-5.00000000e-01-0.j  7.07106781e-01+0.j -5.00000000e-01-0.j]]
[[[1.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 1.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 1.+0.j]]]
Время выполнения: 0.028832 секунд
[[-3.53553391e-01+0.35355339j -7.07106781e-01+0.j
  -3.53553391e-01-0.35355339j]
 [-5.00000000e-01+0.5j         2.22044605e-16+0.j


 20%|██        | 2/10 [00:04<00:18,  2.37s/it]

Время выполнения: 1.712859 секунд
[[-5.00000000e-01+0.j -7.07106781e-01+0.j -5.00000000e-01+0.j]
 [-7.07106781e-01+0.j  2.22044605e-16+0.j  7.07106781e-01+0.j]
 [-5.00000000e-01-0.j  7.07106781e-01+0.j -5.00000000e-01-0.j]]
[[-5.00000000e-01+0.j -7.07106781e-01+0.j -5.00000000e-01+0.j]
 [-7.07106781e-01+0.j  2.22044605e-16+0.j  7.07106781e-01+0.j]
 [-5.00000000e-01-0.j  7.07106781e-01+0.j -5.00000000e-01-0.j]]
[[-5.00000000e-01+0.j -7.07106781e-01+0.j -5.00000000e-01+0.j]
 [-7.07106781e-01+0.j  2.22044605e-16+0.j  7.07106781e-01+0.j]
 [-5.00000000e-01-0.j  7.07106781e-01+0.j -5.00000000e-01-0.j]]
[[[1.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 1.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 1.+0.j]]]
Время выполнения: 0.025595 секунд
[[-3.53553391e-01+0.35355339j -7.07106781e-01+0.j
  -3.53553391e-01-0.35355339j]
 [-5.00000000e-01+0.5j         2.22044605e-16+0.j


 30%|███       | 3/10 [00:06<00:13,  1.99s/it]

Время выполнения: 1.394103 секунд
[[-5.00000000e-01+0.j -7.07106781e-01+0.j -5.00000000e-01+0.j]
 [-7.07106781e-01+0.j  2.22044605e-16+0.j  7.07106781e-01+0.j]
 [-5.00000000e-01-0.j  7.07106781e-01+0.j -5.00000000e-01-0.j]]
[[-5.00000000e-01+0.j -7.07106781e-01+0.j -5.00000000e-01+0.j]
 [-7.07106781e-01+0.j  2.22044605e-16+0.j  7.07106781e-01+0.j]
 [-5.00000000e-01-0.j  7.07106781e-01+0.j -5.00000000e-01-0.j]]
[[-5.00000000e-01+0.j -7.07106781e-01+0.j -5.00000000e-01+0.j]
 [-7.07106781e-01+0.j  2.22044605e-16+0.j  7.07106781e-01+0.j]
 [-5.00000000e-01-0.j  7.07106781e-01+0.j -5.00000000e-01-0.j]]
[[[1.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 1.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 1.+0.j]]]
Время выполнения: 0.025306 секунд
[[-3.53553391e-01+0.35355339j -7.07106781e-01+0.j
  -3.53553391e-01-0.35355339j]
 [-5.00000000e-01+0.5j         2.22044605e-16+0.j


 40%|████      | 4/10 [00:09<00:14,  2.34s/it]

Время выполнения: 2.781584 секунд
[[-5.00000000e-01+0.j -7.07106781e-01+0.j -5.00000000e-01+0.j]
 [-7.07106781e-01+0.j  2.22044605e-16+0.j  7.07106781e-01+0.j]
 [-5.00000000e-01-0.j  7.07106781e-01+0.j -5.00000000e-01-0.j]]
[[-5.00000000e-01+0.j -7.07106781e-01+0.j -5.00000000e-01+0.j]
 [-7.07106781e-01+0.j  2.22044605e-16+0.j  7.07106781e-01+0.j]
 [-5.00000000e-01-0.j  7.07106781e-01+0.j -5.00000000e-01-0.j]]
[[-5.00000000e-01+0.j -7.07106781e-01+0.j -5.00000000e-01+0.j]
 [-7.07106781e-01+0.j  2.22044605e-16+0.j  7.07106781e-01+0.j]
 [-5.00000000e-01-0.j  7.07106781e-01+0.j -5.00000000e-01-0.j]]
[[[1.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 1.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 1.+0.j]]]
Время выполнения: 0.025341 секунд
[[-3.53553391e-01+0.35355339j -7.07106781e-01+0.j
  -3.53553391e-01-0.35355339j]
 [-5.00000000e-01+0.5j         2.22044605e-16+0.j
